package BillingServiceModule;


/**
* BillingServiceModule/BillingService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 19 апреля 2017 г. 10:35:00 EEST
*/

public interface BillingService extends BillingServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillingService
