package BillingServiceModule;


/**
* BillingServiceModule/BillingServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 19 апреля 2017 г. 10:35:00 EEST
*/

public interface BillingServiceOperations 
{
  void addNewCard (String personName, String card);
  void addMoney (String card, double money);
  void subMoney (String card, double money);
  double getCardBalance (String card);
} // interface BillingServiceOperations
